name: rawanaman
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  camera: ^0.11.0+2 #Kamera
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.0.8
  cloud_firestore: ^5.4.4
  path_provider: ^2.1.5
  path: ^1.9.0
  image_picker: ^1.1.2
  dotted_border: ^2.1.0
  animations: ^2.0.11
  google_generative_ai: ^0.4.6
  image: ^3.0.1
  http: ^1.2.2
  table_calendar: ^3.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/icons/green/
    - assets/svgs/
    - assets/model/
